name: micard
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0




flutter:
  uses-material-design: true


  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf

  - family: SansSource3-italic
    fonts:
    - asset: fonts/SourceSans3-Italic-VariableFont_wght.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
